### ISSUE TITLE
IndentationError

### ISSUE THREAD

**Issue by ghost** [stfl/apt-fast-mirrors#2]
line 92
 print(buf)
IndentationError: unindent does not match any outer indentation level

Pls suggest solution. 
Best regards

**Comment by stfl** [comment]
should be fixed now. please check.
I don't actually have a Debian system around to check..

**Comment by ghost** [comment]
The error now is

╰─ sudo python3 af-mirrors.py
Traceback (most recent call last):
  File "af-mirrors.py", line 3, in <module>
    from subprocess import Popen, PIPE, STDOUT, STDERR
ImportError: cannot import name 'STDERR' from 'subprocess' (/usr/lib/python3.8/subprocess.py)

**Comment by stfl** [comment]
Ok. So might be a compatibility issue with python 3.8

**Comment by ghost** [comment]
Which version should be compatible pls?

**Comment by stfl** [comment]
I have not used this script in a long time.
try an older version of python 3.5 or 3.6.
or try to adapt to 3.8.. it looks like the API for subprocess module has changed.

PR welcome
